### PR TITLE
Fix hipMemcpy3D

### LINKED ISSUE #1790: `hipMemcpy3D` is broken
`hipMemcpy3D` is working incorrectly. When I copy a array's with different pitch the destination offset is wrong.

The example is slicing a 4x4x4 integer *C pointer array*
  - the offset is 3x0x0 and applied directly to the pointer addresses
  - the extent is 1x3x3
The destination array is initialized with the value `133` and the values in the source array are enumerated.

```C++
#include <stdio.h>
#include <hip_runtime.h>


__global__ void Fill(int* ptr, size_t pitch, const int numElements)
{
    for(int z = 0; z < numElements; ++z)
    {
        for(int y = 0; y < numElements; ++y)
        {
            for(int x = 0; x < numElements; ++x)
            {
                int idx = z * numElements * numElements + y * numElements + x;
                ((int*)((char*)ptr + z * numElements * pitch + y * pitch))[x] = idx;
            }
        }
    }
}

int main(int argc, char *argv[])
{

    hipPitchedPtr dPtr;

    auto extent = make_hipExtent(4 * sizeof(int),4,4);

    hipMalloc3D(&dPtr, extent);

    int* hPtr;
    hipMallocHost((void**)&hPtr, sizeof(int)*4*4*4);

    for(int i = 0; i < 4 * 4 * 4; ++i)
    {
        hPtr[i] = 133;
    }


    hipLaunchKernelGGL(HIP_KERNEL_NAME(Fill),1,1,0,0,(int*)dPtr.ptr,dPtr.pitch, 4);

    auto srcColumn = make_hipPitchedPtr(
        (char*)dPtr.ptr + 3 * sizeof(int),
        dPtr.pitch,
        4,
        4
    );

    auto dstColumn = make_hipPitchedPtr(
        hPtr + 3,
        4 * sizeof(int),
        4,
        4
    );

    auto copyExtent = make_hipExtent(1*sizeof(int),3,3);

    hipMemcpy3DParms window;
    window.srcArray = nullptr;
    window.dstArray = nullptr;

    window.srcPtr = srcColumn;
    window.srcPos = make_hipPos(0,0,0);
    window.dstPtr = dstColumn;
    window.dstPos = make_hipPos(0,0,0);
    window.extent = copyExtent;
    window.kind = hipMemcpyDeviceToHost;
    
    hipMemcpy3D(
        &window
    );

    hipError_t err = hipGetLastError();
    if( hipSuccess != err) 
       printf("error: %s\n", hipGetErrorString( err));

    for(int z = 0; z < 4; ++z)
    {
        for(int y = 0; y < 4; ++y)
        {
            for(int x = 0; x < 4; ++x)
            {
                int idx = z * 4 * 4 + y * 4 + x;

                printf("%i ", hPtr[idx]);
            }
            printf("\n");
        }
        printf("\n");
        printf("\n");
    }
}
```

output is:
```
133 133 133 3 
133 133 133 7 
133 133 133 11 
133 133 133 19 


133 133 133 23 
133 133 133 27 
133 133 133 35 
133 133 133 39 


133 133 133 43 
133 133 133 133 
133 133 133 133 
133 133 133 133 


133 133 133 133 
133 133 133 133 
133 133 133 133 
133 133 133 133
```
but should be

```
133 133 133 3 
133 133 133 7 
133 133 133 11 
133 133 133 133 


133 133 133 19 
133 133 133 23 
133 133 133 27 
133 133 133 133 


133 133 133 35 
133 133 133 39 
133 133 133 43 
133 133 133 133 


133 133 133 133 
133 133 133 133 
133 133 133 133 
133 133 133 133
```

The bug is a wrong offset in the destination array.
https://github.com/ROCm-Developer-Tools/HIP/blob/753277422a0637ff2bf541c7b43dfaaa2b12c9f6/src/hip_memory.cpp#L1673-L1674
is must be
```C++
unsigned char* dst = (unsigned char*)dstPtr + i * p->dstPtr.ysize * dstPitch + j * dstPitch;
```

### PR DESCRIPTION
**Pull request by gargrahul**
Fixes #1790 and #1791. hipMemcpy3D still requires further refactoring for different input and output combinations.

### CODE REVIEW

File: src/hip_memory.cpp [hunk 1]
```diff
@@ -1540,111 +1540,136 @@ hipError_t hipMemcpyAtoH(void* dst, hipArray* srcArray, size_t srcOffset, size_t
...
+                    stream->locked_copyAsync((void*)dstPtr, (void*)srcPtr, copyWidth*copyHeight*copyDepth, p->kind);
                 else
-                    stream->locked_copySync((void*)dstPtr, (void*)srcPtr, widthInBytes*height*depth, p->kind, false);
+                    stream->locked_copySync((void*)dstPtr, (void*)srcPtr, copyWidth*copyHeight*copyDepth, p->kind, false);
             } else {
-                for (int i = 0; i < depth; i++) {
-                    for (int j = 0; j < height; j++) {
-                        // TODO: p->srcPos or p->dstPos are not 0.
+                for (int i = 0; i < copyDepth; i++) {
+                    for (int j = 0; j < copyHeight; j++) {
```
Comment (emankov) [inline src/hip_memory.cpp]: ++i
++j

File: include/hip/hcc_detail/driver_types.h [hunk 2]
```diff
@@ -254,14 +254,14 @@ typedef struct hipMemcpy3DParms {
...
-
     hipArray_t dstArray;
     struct hipPos dstPos;
     struct hipPitchedPtr dstPtr;
-
     struct hipExtent extent;
     enum hipMemcpyKind kind;
+} hipMemcpy3DParms;
 
+typedef struct HIP_MEMCPY3D {
```
Comment (emankov) [inline include/hip/hcc_detail/driver_types.h]: Thank's for splitting RT's and Driver's structs - it is a headache supporting it in hipify-clang. Are you going to use HIP_MEMCPY3D struct further in Driver's related HIP code?

File: src/hip_memory.cpp [hunk 3]
```diff
@@ -1540,111 +1540,136 @@ hipError_t hipMemcpyAtoH(void* dst, hipArray* srcArray, size_t srcOffset, size_t
...
+                    byteSize = sizeof(uint32_t);
+                    break;
+                case 16:
+                    byteSize = sizeof(uint16_t);
+                    break;
+                case 8:
+                    byteSize = sizeof(uint8_t);
+                    break;
+                default:
+                    byteSize = sizeof(uint32_t);
```
Comment (emankov) [inline src/hip_memory.cpp]: Here and all below: conjunct default branch with a corresponding case.

File: src/hip_memory.cpp [hunk 4]
```diff
@@ -1540,111 +1540,136 @@ hipError_t hipMemcpyAtoH(void* dst, hipArray* srcArray, size_t srcOffset, size_t
...
         void* srcPtr;void* dstPtr;
+        copyDepth = p->extent.depth;
+        copyHeight = p->extent.height;
+        copyWidth =  p->extent.width; // in bytes ?
+        dstXoffset = p->dstPos.x;
+        dstYoffset = p->dstPos.y;
+        dstZoffset = p->dstPos.z;
+        srcXoffset = p->srcPos.x;
+        srcYoffset = p->srcPos.y;
+        srcZoffset = p->srcPos.z;
```
Comment (emankov) [inline src/hip_memory.cpp]: Here and below: I'd think about hipMemcpy3DParms struct var on the stack for copying routines.

File: src/hip_memory.cpp [hunk 5]
```diff
@@ -1540,111 +1540,136 @@ hipError_t hipMemcpyAtoH(void* dst, hipArray* srcArray, size_t srcOffset, size_t
...
+            //Non Array destination
             dstPtr = p->dstPtr.ptr;
-            ySize = p->srcPtr.ysize;
+            dstWidth = p->dstPtr.xsize;
+            dstHeight = p->dstPtr.ysize;
             dstPitch = p->dstPtr.pitch;
         }
 
+        if (p->srcArray != nullptr) {
+            if ((p->srcArray->isDrv == true) ||( p->srcPtr.ptr!= nullptr)){
```
Comment (emankov) [inline src/hip_memory.cpp]: Excessive brackets.

File: src/hip_memory.cpp [hunk 6]
```diff
@@ -1540,111 +1540,136 @@ hipError_t hipMemcpyAtoH(void* dst, hipArray* srcArray, size_t srcOffset, size_t
...
+            srcPtr = p->srcPtr.ptr;
+            srcWidth = p->srcPtr.xsize;
+            srcHeight = p->srcPtr.ysize;
+            srcPitch = p->srcPtr.pitch;
+        }
+
         stream = ihipSyncAndResolveStream(stream);
         try {
-            if((widthInBytes == dstPitch) && (widthInBytes == srcPitch)) {
+            if((copyWidth == dstPitch) && (copyWidth == srcPitch)&& (copyHeight == dstHeight) &&(copyHeight == srcHeight)) {
```
Comment (emankov) [inline src/hip_memory.cpp]: Excessive brackets.
